//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Preston.Media.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Preston.Media.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlbumArtistButtonImage {
            get {
                object obj = ResourceManager.GetObject("AlbumArtistButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DropFileHere {
            get {
                object obj = ResourceManager.GetObject("DropFileHere", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;new ID3V1 tag&gt;.
        /// </summary>
        internal static string NewV1TagPrompt {
            get {
                return ResourceManager.GetString("NewV1TagPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;new ID3V2 tag&gt;.
        /// </summary>
        internal static string NewV2TagPrompt {
            get {
                return ResourceManager.GetString("NewV2TagPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Note {
            get {
                object obj = ResourceManager.GetObject("Note", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appy.
        /// </summary>
        internal static string tteBtnApplyText {
            get {
                return ResourceManager.GetString("tteBtnApplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string tteBtnCancelText {
            get {
                return ResourceManager.GetString("tteBtnCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change File Name.
        /// </summary>
        internal static string tteBtnChangeFileNameText {
            get {
                return ResourceManager.GetString("tteBtnChangeFileNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Tag.
        /// </summary>
        internal static string tteBtnDeleteTagText {
            get {
                return ResourceManager.GetString("tteBtnDeleteTagText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string tteBtnOkText {
            get {
                return ResourceManager.GetString("tteBtnOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Tag Editor.
        /// </summary>
        internal static string tteFormName {
            get {
                return ResourceManager.GetString("tteFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Tag Editor.
        /// </summary>
        internal static string tteFormText {
            get {
                return ResourceManager.GetString("tteFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose tag to view:.
        /// </summary>
        internal static string tteLblChooseTagText {
            get {
                return ResourceManager.GetString("tteLblChooseTagText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop MP3 file here....
        /// </summary>
        internal static string tteLblFileNameText {
            get {
                return ResourceManager.GetString("tteLblFileNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected..
        /// </summary>
        internal static string tteLblNoFileSelectedText {
            get {
                return ResourceManager.GetString("tteLblNoFileSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track file name:.
        /// </summary>
        internal static string tteLblTrackFileNameText {
            get {
                return ResourceManager.GetString("tteLblTrackFileNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show File List.
        /// </summary>
        internal static string tteTsbShowFileListText {
            get {
                return ResourceManager.GetString("tteTsbShowFileListText", resourceCulture);
            }
        }
    }
}
